### ISSUE TITLE
FTBFS with gcc 15

### ISSUE THREAD

**Issue by kartikm** [spbooth/xmountains#13]
xmountains fails to build with gcc 15. See the downstream bug from Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1098157

[...]
      |                                 ^~~~~~~~~~~
      |                                 |
      |                                 void (*)(void)
In file included from xmountains.c:5:
/usr/include/signal.h:88:57: note: expected ‘__sighandler_t’ {aka ‘void (*)(int)’} but argument is of type ‘void (*)(void)’
   88 | extern __sighandler_t signal (int __sig, __sighandler_t __handler)
      |                                          ~~~~~~~~~~~~~~~^~~~~~~~~
xmountains.c:98:6: note: ‘finish_prog’ declared here
   98 | void finish_prog();
      |      ^~~~~~~~~~~
/usr/include/signal.h:72:16: note: ‘__sighandler_t’ declared here
   72 | typedef void (*__sighandler_t) (int);
      |                ^~~~~~~~~~~~~~
xmountains.c:438:34: error: passing argument 2 of ‘signal’ from incompatible pointer type [-Wincompatible-pointer-types]
  438 |   if( SIG_ERR == signal(SIGTERM, finish_prog ))
      |                                  ^~~~~~~~~~~
      |                                  |
      |                                  void (*)(void)
/usr/include/signal.h:88:57: note: expected ‘__sighandler_t’ {aka ‘void (*)(int)’} but argument is of type ‘void (*)(void)’
   88 | extern __sighandler_t signal (int __sig, __sighandler_t __handler)
      |                                          ~~~~~~~~~~~~~~~^~~~~~~~~
xmountains.c:98:6: note: ‘finish_prog’ declared here
   98 | void finish_prog();
      |      ^~~~~~~~~~~
/usr/include/signal.h:72:16: note: ‘__sighandler_t’ declared here
   72 | typedef void (*__sighandler_t) (int);
      |                ^~~~~~~~~~~~~~
xmountains.c:443:33: error: passing argument 2 of ‘signal’ from incompatible pointer type [-Wincompatible-pointer-types]
  443 |   if( SIG_ERR == signal(SIGHUP, finish_prog ))
      |                                 ^~~~~~~~~~~
      |                                 |
      |                                 void (*)(void)
/usr/include/signal.h:88:57: note: expected ‘__sighandler_t’ {aka ‘void (*)(int)’} but argument is of type ‘void (*)(void)’
   88 | extern __sighandler_t signal (int __sig, __sighandler_t __handler)
      |                                          ~~~~~~~~~~~~~~~^~~~~~~~~
xmountains.c:98:6: note: ‘finish_prog’ declared here
   98 | void finish_prog();
      |      ^~~~~~~~~~~
/usr/include/signal.h:72:16: note: ‘__sighandler_t’ declared here
   72 | typedef void (*__sighandler_t) (int);
      |                ^~~~~~~~~~~~~~
xmountains.c:448:34: error: passing argument 2 of ‘signal’ from incompatible pointer type [-Wincompatible-pointer-types]
  448 |   if( SIG_ERR == signal(SIGQUIT, finish_prog ))
      |                                  ^~~~~~~~~~~
      |                                  |
      |                                  void (*)(void)
/usr/include/signal.h:88:57: note: expected ‘__sighandler_t’ {aka ‘void (*)(int)’} but argument is of type ‘void (*)(void)’
   88 | extern __sighandler_t signal (int __sig, __sighandler_t __handler)
      |                                          ~~~~~~~~~~~~~~~^~~~~~~~~
xmountains.c:98:6: note: ‘finish_prog’ declared here
   98 | void finish_prog();
      |      ^~~~~~~~~~~
/usr/include/signal.h:72:16: note: ‘__sighandler_t’ declared here
   72 | typedef void (*__sighandler_t) (int);
      |                ^~~~~~~~~~~~~~
make[1]: *** [<builtin>: calcalt.o] Error 1
make[1]: *** [<builtin>: xmountains.o] Error 1
make[1]: *** [<builtin>: artist.o] Error 1
random.c: In function ‘rstart’:
random.c:59:6: warning: old-style function definition [-Wold-style-definition]
   59 | void rstart(i,j,k,l)
      |      ^~~~~~
random.c: In function ‘seed_uni’:
random.c:102:6: warning: old-style function definition [-Wold-style-definition]
  102 | void seed_uni(ijkl)
      |      ^~~~~~~~
make[1]: Leaving directory '/build/reproducible-path/xmountains-2.11'

**Comment by spbooth** [comment]
I don't have gcc-15 readily at hand but I've committed some changes based on the error messages
* Updated the signatures in random.c to modern cyntax
* switched from using signal to sigaction

**Comment by spbooth** [comment]
issues addressed in latest release

**Comment by kartikm** [comment]
It seems we still have a build failure. Please review the attached logs. 

[xmountains-2.13.build.log](https://github.com/user-attachments/files/22247010/xmountains-2.13.build.log)

**Comment by spbooth** [comment]
Problem seems to be related to old-style function definitions.  I've expunged these

**Comment by kartikm** [comment]
With the latest build,

gcc -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fstack-clash-protection -Wdate-time -D_FORTIFY_SOURCE=2  -c -o print_alg.o print_alg.c
X_graphics.c:83:6: error: conflicting types for 'zap_events'; have 'void(int)'
   83 | void zap_events(int snooze)
      |      ^~~~~~~~~~
X_graphics.c:50:6: note: previous declaration of 'zap_events' with type 'void(void)'
   50 | void zap_events();
      |      ^~~~~~~~~~
make[1]: *** [<builtin>: X_graphics.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/build/xmountains-2.14'
dh_auto_build: error: make -j8 "INSTALL=install --strip-program=true" returned exit code 2
make: *** [debian/rules:8: binary] Error 25
dpkg-buildpackage: error: debian/rules binary subprocess returned exit status 2
I: copying local configuration
E: Failed autobuilding of package

**Comment by spbooth** [comment]
Dang missed one. Also updated the manpage in the v2.15 release
